--DESCRIBE THE STRUCTURE OF THE TABLES
DESCRIBE FACULTY;
DESCRIBE STUDENT;
DESCRIBE COURSE;
DESCRIBE ENROLLMENT;

--DISPLAY ALL TABLES
SELECT * FROM FACULTY;
SELECT * FROM STUDENT;
SELECT * FROM COURSE;
SELECT * FROM ENROLLMENT;
