---
title: "Project 4"
author: "Lakshmi Mounica Marupeddi"
date: "2024-07-08"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown
```{r}
library(tidyverse)
df = read_csv("/Users/lakshmimounicamarupeddi/Desktop/DSC 441/Project_4/ames_alcohol_test1.csv")
glimpse(df)
library(dplyr)

```

# Question 1
```{r}
# How many rows and columns are there in the data
glimpse(df)
```

# Question 2
```{r}
# Which years were the data recorded?
unique(df$year)

```

# Question 3
```{r}
#Which year has the most number of data points?
temp = df %>% group_by(year) %>% summarize(maxData = n()) %>% arrange(-maxData)
temp %>% ggplot(aes(x=year, y=maxData)) + geom_col() + ggtitle("Data Points For Each Year")

```



# Question 4
```{r}
#What is the busiest police department? 
temp = df %>% group_by(location) %>% count()
temp
```
# Question 5
```{r}
#Which hour is the most popular time for alcohol tests?
temp = df %>% 
  group_by(hour) %>% 
  summarize(freqOfhours = n()) %>% 
  filter(freqOfhours == max(freqOfhours))
temp

# df %>% count(hour) 
```
# Question 6
```{r}
#In 2017, how many tests were done in January through March? (both months are included)
# Solution
df %>% filter(year == 2017 & month %in% c(1:3)) %>% summarize(count = n()) 
# Visualization
df %>% filter(year == 2017 & month %in% c(1:3)) %>% group_by(month) %>% summarize(tests = n()) %>% ggplot(aes(x=month, y=tests)) + geom_line(linewidth = 1) + geom_point(size = 3, color = "red") + ggtitle("Number of tests from January to March")
```

# Question 7
```{r}
#In each year, which month is the most common for alcohol tests? (Expecting to see the count of tests for each month in each year.)    

temp = df %>% group_by(year, month) %>% summarize(testCount = n()) %>% select(month, testCount, year)
final = temp %>% group_by(year) %>% filter(testCount == max(testCount))
final 
ggplot(final, aes(x=year, y = testCount, fill = as.factor(month) ) )+ geom_col() + ggtitle("Most Common Month for Alcohol Tests each Year")
```


# Question 8
```{r}
# How many alcohol tests are males and females administered?
df %>% group_by(sex)  %>% count()
```


# Question 9
```{r}
# The sex variable has missing values. Only select those rows where the sex variable is not missing. Hint: Make use of !is.na() # function. Save this dataframe as df_clean.
# In df_clean, create a new column called `Res` which is the average of Res1 and Res2 (Res = (Res1+Res2)/2). When you compare # # the average of the "Res" for the two sexes, which sex has larger average alcohol content (Average Res value) in their breath #test?
df
df_clean = df %>% filter(!is.na(sex))
df_clean %>% mutate(Res = (Res1+Res2)/2) %>% group_by(sex) %>% summarize(avgs = mean(Res))

```
# Question 10
```{r}
# Blood alcohol content (BAC) above 0.08% means Driving Under Influence (DUI). If either test 1 or test 2 is above 0.08% then that person will be charged with DUI. What is the percentage of people who were charged with DUI?  
d1 = df %>% filter(Res1 > 0.08|Res2 >0.08) %>% count()
d2 = df %>% count
(d1$n / d2$n) * 100
```

# Question 11
```{r}
# What's the percentage of people that have 0% BAC in either the first or the second test? 
d11 = df %>% filter(Res1 <= 0|Res2 <= 0) %>% count()
(d11/d2) *100
```
# Question 12
```{r}
# Order the months based on the percentage of DUI cases from large to small. Do not separate out by year - just check the months. What are the first 4 months in order?
# For this we will need to create a new variable that encodes 1 for DUI cases, and 0 for non-DUI cases, and then find the number of total tests for each month. Then we can find which month has the largest percentage of DUI cases. Hint: Make use of mutate() and ifelse() functions to create the "dui" variable.
 
  
d = df %>%  mutate(DUI = 
                     ifelse((Res1 > 0.08|Res2 > 0.08), 1, 0 ))

df1= df %>% group_by(month) %>% summarize(testCount = n()) 
df2 = d %>% filter(DUI == 1) %>% group_by(month) %>% count()
finaldf = (df2[2]/df1[2]) * 100

df1 %>% mutate(percentages = finaldf$n) %>% arrange(-percentages)


```
