--drop tables if exists
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE CUSTOMERS';
    
    EXECUTE IMMEDIATE 'DROP TABLE EMPLOYEES';
    EXECUTE IMMEDIATE 'DROP TABLE ZIPCODES';
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('');
END;
/

CREATE TABLE ZIPCODES (
    ZIP CHAR(5),
    CITY VARCHAR2(50),
    PRIMARY KEY (ZIP)
);
                
CREATE TABLE CUSTOMERS (
    CNO VARCHAR2(10),
    CNAME VARCHAR2(50),
    STREET VARCHAR2(100),
    ZIP CHAR(5),
    PHONE VARCHAR2(15),
    PRIMARY KEY (CNO),
    FOREIGN KEY (ZIP) REFERENCES ZIPCODES(ZIP)
);

CREATE TABLE EMPLOYEES (
    ENO VARCHAR2(10) ,
    ENAME VARCHAR2(50),
    ZIP CHAR(5),
    HDATE DATE,
    PRIMARY KEY (ENO),
    FOREIGN KEY (ZIP) REFERENCES ZIPCODES(ZIP)
);
--